spring.application.name=${APP_NAME:spring-boot-crud-with-mysql}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/spring-boot-a5}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Sharfu@8826}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}

server.port=${SERVER_PORT:8183}