spring.application.name=spring-boot-crud-with-mysql

spring.datasource.url=jdbc:mysql://localhost:3306/spring-boot-a5
spring.datasource.username=root
spring.datasource.password=Sharfu@8826

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8183