apiVersion: v1
kind: Secret
metadata:
  name: springoot-secret
  namespace: spring-app-ns
type: Opaque
data:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: U2hhcmZ1QDg4MjY=
  MYSQL_ROOT_PASSWORD: U2hhcmZ1QDg4MjY=
