apiVersion: apps/v1
kind: Deployment

metadata:
  name: springboot-app
  namespace: spring-app-ns

spec:
  replicas: 1

  selector:
    matchLabels:
      app: springboot

  template:
    metadata:
      labels:
        app: springboot

    spec:
      containers:
      - name: springboot

        image: sharfuddin47/spring-boot-crud-with-mysql:latest

        ports:
        - containerPort: 8183

        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: APP_NAME

        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: DB_URL

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: springoot-secret
              key: DB_USERNAME

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springoot-secret
              key: DB_PASSWORD

        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: springboot-config
              key: SERVER_PORT